@startuml
autonumber
!pragma teoz true

box "PC1 (192.168.1.57)" #LightBlue
  box "response-sample"
    participant "sample.cpp" as sender
    participant "vsomeip::application" as app
  end box
  participant "routingmanager" as routmgr
end box

sender->app **:  vomeip::runtime::get()->create_application(VSOMEIP_APPLICATION_NAME)
sender->app: init()
app->app: loadConfig(VSOMEIP_CONFIGURATION)
sender->app: register_state_handler(on_state)
app->routmgr: VSOMEIP_REGISTER_APPLICATION (0x02)
sender->app: register_availability_handler(SAMPLE_SERVICE_ID, SAMPLE_INSTANCE_ID, on_availability)
sender->app: register_message_handler(SAMPLE_SERVICE_ID, SAMPLE_INSTANCE_ID, SAMPLE_METHOD_ID, on_message)
sender->app: start()
return true

routmgr->app: VSOMEIP_REGISTERED_ACK (0x06)
app->sender: on_state(vsomeip::state_type_e _state)
opt _state = vsomeip::state_type_e::ST_REGISTERED
sender->app: **<color blue>offer_service</color>**(SAMPLE_SERVICE_ID, SAMPLE_INSTANCE_ID)
app->routmgr: OFFER_SERVICE(...)
end

===receive request and send response==
app->sender: on_message(_message{SAMPLE_SERVICE_ID, SAMPLE_INSTANCE_ID, SAMPLE_METHOD_ID, reliable, payload})
sender->sender: create_response(_message).setpayload(...)  -> its_response
sender->app: **<color blue>send</color>**(its_response)
@endtuml