name: Render All PlantUML Diagrams

on:
  push:
    paths:
      - '**/*.puml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install PlantUML
        run: sudo curl -L -o plantuml.jar https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar

      - name: Render all .puml files to .svg
        run: |
          find . -type f -name '*.puml' | while read file; do
            echo "Rendering $file..."
            java -jar plantuml.jar -tsvg "$file"
          done

      - name: Show current branch and user
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Actor: ${{ github.actor }}"
          git status
          git branch -a

      - name: Debug Show git remote before push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "GITHUB_TOKEN length: ${#GITHUB_TOKEN}"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git remote -v

      - name: Commit rendered SVGs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add '*.svg' ':!*.svg.lock'
          git commit -m "Auto-render: update all PlantUML diagrams to SVG" || echo "No changes"
          git push origin HEAD:${{ github.ref_name }}